# Generated by Django 4.1.3 on 2023-10-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_account_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=5),
        ),
    ]
